version: '3.7'

services:
  web:
    image: nginx
    ports:
      - "80:80"
    configs:
      - source: nginx_default_conf
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx_default_conf:
    external: true
