version: '3.8'

services:
  app:
    image: my-golang-app
    ports:
      - "8080:8080"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myapp.rule=Host(`myapp.com`)"
        - "traefik.http.services.myapp.loadbalancer.server.port=8080"
      replicas: 1
    networks:
      - my-overlay

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - my-overlay

networks:
  my-overlay:
    driver: overlay

volumes:
  postgres_data:
