version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
    networks:
      - my-overlay

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - my-overlay

networks:
  my-overlay:
    driver: overlay

volumes:
  postgres_data:
