version: '3.3'

services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1

volumes:
  registry_data:
