version: '3.3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: demo
    secrets:
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-overlay
    configs:
      - source: init_data_sql
        target: /docker-entrypoint-initdb.d/init-data.sql

  app:
    image: 192.168.56.101:5000/go-app
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    environment:
      POSTGRES_PASSWORD: abc123-   # Thêm biến môi trường POSTGRES_PASSWORD để go có thể bắt được mật khẩu của postgres
    deploy:
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.myapp.rule=Host(`domain.lc`)"
        - "traefik.http.services.myapp.loadbalancer.server.port=8088"
    networks:
      - my-overlay
      - traefik-net
    secrets:
      - postgres_password

  web:
    image: 192.168.56.101:5000/my-web
    ports:
      - "8090:8090"
    networks:
      - my-overlay
      - traefik-net
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myweb.rule=Host(`domain.lc`)"
      - "traefik.http.routers.myweb.entrypoints=web"

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    networks:
      - my-overlay

volumes:
  postgres_data:

networks:
  my-overlay:
    driver: overlay
  traefik-net: 
    external: true

secrets:
  postgres_password:
    external: true

configs:
  nginx_conf:
    external: true    